### ISSUE TITLE
Should be able to Ctrl+C on an input that is required

### ISSUE THREAD

**Issue by mholt** [AlecAivazis/survey#10]
When a question uses survey.Required to validate the input, it forbids quitting with Ctrl+C. That doesn't seem useful to me. :wink: Is that intentional?

**Comment by AlecAivazis** [comment]
Ha! Whoops. I suppose that is a problem. Thanks for another very helpful bug report! I'll get on this ASAP.

**Comment by mholt** [comment]
So, strangely I can't reproduce this anymore (without applying your changes). :confused: Were you able to?

**Comment by AlecAivazis** [comment]
Yea, I was able to reproduce this for `Choice` prompts which makes sense given its implementation. I'm pretty sure `Input` works as expected. Are you not seeing the wrong behavior on `Choice`s?

**Comment by mholt** [comment]
Oh right it was Choice, I was trying again on Input. Nevermind. :blush:
