### ISSUE TITLE
Survey forces me to use []survey.Question for every occasion

### ISSUE THREAD

**Issue by frodgesh** [AlecAivazis/survey#106]
Is it possible to use `Validate` field from `[]survey.Question` within any other function, except `Ask`? So it goes like every time we need to use `Validate` or `Transform`, we have to create a new question array and use it only with `Ask`, even if it isn't supposed to ask more, than one question. To make things less complicated, I suggest to leave only `Ask` function cause it carries all the stuff other functions do.

**Comment by AlecAivazis** [comment]
@frodgesh thanks for submitting another issue. I'm slightly confused what exactly you're asking -  do you mind providing a code block for the API you would like to see?

**Comment by frodgesh** [comment]
@AlecAivazis, sorry about my explanation. I'm just asking, if it's possible to use Validation above the survey.AskOne().

**Comment by kataras** [comment]
@frodgesh I'm not sure if I understand correctly but I'll try to answer you based on the question I can imagine that you're asking for;

`Validator` is just a function of form: `func(ans interface{}) error` , the `ans` is the answer given from the user by terminal and if the returned error is not nil then the answer is invalid and it asks again. 

You can use it anywhere you like, remember they're just functions, the `AskOne` is just a helper which you can pass a `nil` on its third input argument if you don't want them.

You can use `Validators` all over the place, look the README.md example, it has a `Validation: ` field on `Question` struct: https://github.com/AlecAivazis/survey/blob/master/survey.go#L28 but this doesn't limit you to use those functions in other places inside your project as well!

**Comment by frodgesh** [comment]
@kataras, I don't even know, how did I pass away the third argument, sorry about my clumsiness. And what about using `Transform` field in the helper's function?

**Comment by AlecAivazis** [comment]
Thanks for helping out @kataras, I hope this clears things up for you @frodgesh.

I was just thinking about whether or not we wanted to include a `Transformer` as an arg to `AskOne`. Since `Transformers` are just normal functions, you can perform the transformation on the variable after calling `AskOne`. This allows us to avoid adding an additional argument to `AskOne` which saves us breaking the API.

**Comment by frodgesh** [comment]
@AlecAivazis, I didn't get the point of Transformer since we can manipulate with string as we'd like too, so yep.

**Comment by kataras** [comment]
No problem, yes I didn't add those on `AskOne` for the same reason, although I think that `AskOne` should be avoided because we can't add many input arguments as struct fields on the `Ask(...,Question)`

**Comment by frodgesh** [comment]
@kataras, you said the exact reason, why did I open the issue.
