### ISSUE TITLE
Conditionally prevent signals trapping

### ISSUE THREAD

**Issue by streambinder** [AlecAivazis/survey#111]
It seems that a simple survey like this:
```
ans := false
prompt := &survey.Confirm{
	Message: prompt_message,
}
survey.AskOne(prompt, &ans, nil)
```
is overriding SIGINT action, preventing my own application to apply its own trapping procedure.
Actually don't know if it's the way it's supposed to work, but in this case I need a way to prevent it to move that way.

**Comment by AlecAivazis** [comment]
Hey @streambinder - thanks for opening this issue.

Interrupts are returned as errors from `AskOne` so if you want to capture it then you could do something like:

```golang
// ...

err := survey.AskOne(prompt, &ans, nil)
if err != nil {
     // handle interrupt here
}
```
Then you should be able to perform whatever logic you want.

Hope this helps!

**Comment by streambinder** [comment]
Thank you, appreciated. :)

**Comment by jordanglassman** [comment]
I appreciate this workaround, but this requires you do add handling for interrupts for every prompt used, which could be a lot.

I have something like this for top-level handling:

```
func HandleUserInterrupt() {
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-c
                pkg.ExitOnInterrupt()
	}()
}
```

and then much duplicated code like this:

```
	err = survey.AskOne(&survey.Confirm{
		Message: "...?",
		Default: true,
		Help:    "...",
	}, &cleanup)
	if err != nil {
		pkg.HandleUserInterrupt(err)
		return errors.WithStack(err)
	}
```

Is there any way to do global configuration to minimize this sort of thing?
