### ISSUE TITLE
Is terminal package adopted from go-ansi

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#112]
https://godoc.org/github.com/AlecAivazis/survey/terminal
https://godoc.org/github.com/k0kubun/go-ansi

They look very similar. If go-ansi is the predecessor, I think they deserve to have credits in godoc (and have their MIT LICENSE included in the tree) for their work.

**Comment by AlecAivazis** [comment]
Definitely. The README in that package used to reference the project, but as we changed it to accomodate survey's specific usecase, the two started to diverge and the internal README was removed. I'm totally open to adding that back tho

**Comment by ahmetb** [comment]
@AlecAivazis Thanks. I think adding a note to package godoc would help people understand its roots. I recently decided to use survey/terminal over k0kubun/go-ansi because it’s more actively maintained. A note on that probably helps.

What do you think about the LICENSE stuff? I am not a lawyer, but I’m not sure if you should be removing k0kubun's MIT license, or relicensing the package as Apache 2.0. 

I’m genuinely curious because I might actually use this package in a commercially distributed software.

**Comment by AlecAivazis** [comment]
That's awesome! So I am not entirely sure what I should do here since `kokuban/go-ansi` doesn't have an actual license file that I can copy into the package inside of `survey`. I have a branch with a readme explaining the packages origin and `survey` is also licensed as MIT (which is supposedly the license for `go-ansi`). Do you think this is enough?

**Comment by AlecAivazis** [comment]
@ahmetb - i just submitted a PR that adds the license into the terminal package. Thanks again for bringing this to my attention!

**Comment by AlecAivazis** [comment]
@ahmetb I'm going to close this since that PR has been merged
