### ISSUE TITLE
Similar project: promptui

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#113]
Just spotted this on GitHub: https://github.com/manifoldco/promptui

I thought you might want to know in case you missed its release.

Would be good to have a comparison section in README.md.

**Comment by AlecAivazis** [comment]
Oh interesting! It's funny, the source code reminds me a lot of how survey first started. Once @coryb  and I began adding the more complicated interactions, we kept running against `chzyer/readline` which really wants to own a lot of the cursor interactions. It was hard to keep the behavior consistent - hence why we have `survey/terminal` now. The project you linked to has doubled in stars overnight! Maybe I should share a link to survey on hackernews? 🤔 

Regardless, I think adding a comparison doc is good now that promptui seems to have picked up so much traction overnight.
