### ISSUE TITLE
Cannot exit program with ctrl-C while survey is prompting

### ISSUE THREAD

**Issue by ijt** [AlecAivazis/survey#117]
If it's in a loop, I end up having to kill my program from another terminal.

**Comment by AlecAivazis** [comment]
Hey @ijt thanks for reporting you rissue - can you post your prompt/ call to `Ask` or `AskOne`? Interrupts should be returned as errors from those functions.

**Comment by ijt** [comment]
Hi Alec, no problem. Here's what I wrote:

                ok := false
                prompt := &survey.Confirm{
                        Message: fmt.Sprintf("Is version %d ok? ",
nums[mid]),
                }
                survey.AskOne(prompt, &ok, nil)

**Comment by AlecAivazis** [comment]
Thanks! Can you provide a little more context around your problem? When you say `in a loop`, do you mean if the call to `AskOne` is inside of a loop in your code? If so, can you post that loop? 

I just tried to run the confirm tests locally to make sure interrupts were still working and the prompt behaves as expected. While we're at it, can you share your OS/terminal?

**Comment by ijt** [comment]
I see what's going on now. I wasn't checking the error returned from
survey.AskOne(). Now I'm checking it, and it turns out that it returns an
error of "interrupt" if ctrl-C is pressed. I just need to check for that
case and terminate if it's an interrupt.

So this isn't really a bug in your library, which by the way is very nice
to use.

Here is my new and improved function that does what I want:

// bisect interactively finds the first non-ok version number in the nums
slice.
unc bisect(nums []int) {
        lo := 0
        hi := len(nums) - 1
        for {
                mid := (lo + hi) / 2
                fmt.Printf("lo = %d, mid = %d, hi = %d\n", lo, mid, hi)
                fmt.Printf("lo : %d, mid : %d, hi : %d\n", nums[lo],
nums[mid], nums[hi])
                if mid == lo || mid == hi {
                        fmt.Printf("The problem seems to have started with
version %d\n", nums[hi])
                        os.Exit(0)
                }
                ok := false
                prompt := &survey.Confirm{
                        Message: fmt.Sprintf("Is version %d ok? ",
nums[mid]),
                }
                for {
                        err := survey.AskOne(prompt, &ok, nil)
                        switch {
                        case err.Error() == "interrupt":
                                fmt.Println("ctrl-C pressed. Exiting.")
                                os.Exit(1)
                        case err != nil:
                                fmt.Printf("%v. Trying again.\n", err)
                                continue
                        default:
                                break
                        }
                }
                if ok {
                        fmt.Printf("mid is ok => mid is the new lo\n")
                        lo = mid
                } else {
                        fmt.Printf("mid is not ok => mid is the new hi\n")
                        hi = mid
                }
        }
}

**Comment by AlecAivazis** [comment]
Awesome! Glad you got this sorted out. A few people have been confused by the handling of interrupts - I should make that more clear in the docs... 

Please let me know if you run into more problems!
