### ISSUE TITLE
How to access survey/core

### ISSUE THREAD

**Issue by maxchehab** [AlecAivazis/survey#122]
I would like to change a default output character but can't access `survey/core` as said in the README.

How can I access `survey/core`?

Thanks,

Max

**Comment by AlecAivazis** [comment]
Hey @maxchehab, do you mind posting how you are attempting to change it?

**Comment by maxchehab** [comment]
I would like to change `UnmarkedOptionIcon`.

**Comment by AlecAivazis** [comment]
The example in the README "should work". Can you post the code block that's not working for you? I want to try to reproduce your issue

**Comment by AlecAivazis** [comment]
So I was able to verify that I am able to change `survey/core`, however this *is* a problem with the docs. The package-level variable to change is `HelpIcon` not `HelpInputRune`. I'll fix that now. 

note: I was able to verify this by changing the main function in the [confirm tests]() to read 
```
func main() {
	surveyCore.QuestionIcon = "a"
	TestUtil.RunTable(goodTable)
}```

and adding the `surveyCore` import

**Comment by maxchehab** [comment]
I am sorry. I misread the readme.

**Comment by AlecAivazis** [comment]
No problem at all! Lemme know if you run into anything else.
