### ISSUE TITLE
Terminal cursor move/delete does not handle multi-character inputs well 

### ISSUE THREAD

**Issue by mritd** [AlecAivazis/survey#126]
When using the Input component to enter other language characters such as Chinese, the cursor does not move properly when characters are deleted.

![2018-03-07 21_08_38](https://user-images.githubusercontent.com/13043245/37093900-fc6dc848-224b-11e8-8d03-ab1bdae62d1a.gif)

Because [CursorBack function](https://github.com/AlecAivazis/survey/blob/6c118e265bb2c74e38a987746f763c34d5947769/terminal/runereader.go#L62) ignores the utf8 length of the last character, making the cursor always move one character to the left; for Chinese Character cursors should be moved left by 2 characters, but I do not know what other languages should do.

**Comment by AlecAivazis** [comment]
Ah darn! Thanks for bringing this to my attention @mritd! Hopefully this can be addressed soon

**Comment by mritd** [comment]
@AlecAivazis It seems to solve this problem through this library https://github.com/mattn/go-runewidth 😀

**Comment by mritd** [comment]
@AlecAivazis 

I tried to fix this with the go-runewidth library and created a PR, now it looks fine.

refs #180

**Comment by mritd** [comment]
Close this issue.
refs #217
