### ISSUE TITLE
Only 10 lines of buffer on Mac

### ISSUE THREAD

**Issue by coryodaniel** [AlecAivazis/survey#128]
I'm not sure if this is a bug or a config option I haven't found, but on Mac only it appears that there is only 10 lines of screen buffer that are used. Each prompt appears on its own line until it gets to the 10th. At the 10th line new prompts appear here and the 9th line continually gets overwritten.

I dont know if I described that well, I can upload a video if that doesnt make sense.

Awesome tool by the way!

**Comment by AlecAivazis** [comment]
Hey @coryodaniel - thanks for reporting this. 

When you say "only 10 lines of buffer" can you still navigate to see all of your options? If so, this is intended as a "feature not a bug". In order to prevent massive lists of options from being unusable, we paginate the list although it should be showing 7 entries, not 10. Do you mind taking a video so I can figure out if this is working as intended.

Assuming it's working correctly, you can change on a global level by setting `survey.PageSize` or on a  prompt specific level, for example: 

```golang
prompt := &survey.Select{..., PageSize: 10}
```

**Comment by coryodaniel** [comment]
Yeah so you'll see it only supports about 10 lines and then it will overwrite the last one over and over. All of the answers come out as expected, so it seems to just be a UI thing.

Attached a zip w/ the video, thanks!
[survey.zip](https://github.com/AlecAivazis/survey/files/1808880/survey.zip)

**Comment by AlecAivazis** [comment]
Whoa that was confusing, but i think I understand what you're trying to show. Is it possible this is a configuration problem with your terminal? Here is a video of me running through the [select tests](https://github.com/AlecAivazis/survey/blob/master/tests/select.go) in a tall terminal. This is iTerm2 for what it's worth. 

[Untitled.zip](https://github.com/AlecAivazis/survey/files/1808915/Untitled.zip)

**Comment by coryodaniel** [comment]
So, locally the tests run in the same manner as in your video. So it must be something specific to the way Im interacting with the surveys or answers...

I moved the "forms" around (there are three different sets of questions I pass to survey.Ask or survey.AskOne) and it seems to happen around the time I ask to "add another property"...


```go

**Comment by AlecAivazis** [comment]
@coryodaniel - cool, would you mind trying to run through the confirm tests? If that displays correctly, I might need more context around the rest of this code. Those tests run `askOne` repeatedly so I can't see what would be different between them and what you're doing.

**Comment by coryodaniel** [comment]
Those work too. I figured it out.

I had a variable set:
`var myVar = ([]*survey.Question) {...}`

**Comment by AlecAivazis** [comment]
Awesome, I"m glad to hear you got your problem fixed. I haven't tried to modify an existing prompt before so it's interesting to see that you ran into this. Lemme know if you run into any more problems!

**Comment by coryodaniel** [comment]
Will do. Thanks so much. It’s a great tool!
