### ISSUE TITLE
[feature] Allow separate display and value fields for Select & MultiSelect

### ISSUE THREAD

**Issue by djgilcrease** [AlecAivazis/survey#133]
I was thinking something like
```go
type Option struct {
	Display string
	Value interface{}
}
```
this will also allow the value to be a struct not just a string

**Comment by AlecAivazis** [comment]
They @djgilcrease - thanks for submitthing this issue. This seems to be a duplicate of #105 which has a lot of discussion about how one should specify an option as a struct.
