### ISSUE TITLE
Add support for changing the color of the different runes/prompts

### ISSUE THREAD

**Issue by kleoken** [AlecAivazis/survey#141]
Creating a CLI with this currently and would be nice if I could change the color of the QuestionIcon application wide

**Comment by AlecAivazis** [comment]
Hey @Celo44 - thanks for submitting this. I don't know if I will have the time in the near future to add this but if you wanted to give it a stab, I would be happy to review a PR 🙂

**Comment by MarkusFreitag** [comment]
I would start by making the icons configurable. Therefore I would like to evolve to icon, which is currently a `string`, into a `struct` which for now has two fields.
```
type Icon struct {
  Symbol string
  Color    string
}
```
Maybe @AlecAivazis can give some feedback about this approach. If it is accepted I will provide a PR.

**Comment by AlecAivazis** [comment]
Hey @MarkusFreitag - thanks for the input. I like the idea, although I'm not sure if providing this would be too much customizability for the library. Can you maybe share your reason for wanting to change the colors? 

In general, i'm a bit wary of changing the public API for a relatively minor feature. I think I would prefer if there was a way to call something like `surveyCore.SetIcon("ErrorIcon", Icon{Symbol: "!"}) which keeps the top level API the same. In this case, we would add variables for each of the colors, and `SetIcon` would change the values of `ErrorIcon` to the `Symbol` field and the color templates to match that field if provided.

Thoughts? Would that satisfy both of your needs?

**Comment by MarkusFreitag** [comment]
Thanks for your feedback. It does not really changes the API that much. Basically I have just moved the hard-coded color definitions from the template strings into the icon struct and then call `Icon.Color` in the template. Also the `var TemplateFuncs = map[string]interface{}` works as before. I think that it also makes it easier to maintain the library, as you have such things in a central place and not spread over every template. Nevertheless I can push my changes into a branch, which might makes it easier to find a consent on this.

> Can you maybe share your reason for wanting to change the colors?

Passing this question to @Celo44

**Comment by MarkusFreitag** [comment]
@AlecAivazis I put the changes into a separate branch, maybe in the next days you have some time to have a look on them. As written before the API behaviour does not change.
https://github.com/MarkusFreitag/survey/commit/ceb60e1791ab3d800b1fe5957f246e3093900412

**Comment by bmuschko** [comment]
@AlecAivazis Any chance we can move forward with @MarkusFreitag's commit?

**Comment by AlecAivazis** [comment]
@MarkusFreitag I think the solution proposed in #193 is the right way to provide the ability to change the icon color without introducing a bunch of types or new APIs to survey. Do you want to give that a shot? Since it's a soft-break of the API, I think it should be included in the upcoming `[v2 release](https://github.com/AlecAivazis/survey/milestones/1)

**Comment by AlecAivazis** [comment]
@MarkusFreitag since we're preparing to merge the v2 release that will break the API, it's a good opportunity to use the API that you suggested - wanna give it a shot?

**Comment by AlecAivazis** [comment]
#216 adds the `survey.WithIconSet` option which looks a little something like:

```golang
survey.AskOne(prompt, &value, survey.WithIconSet(func icons survey.IconSet) {
    icons.Question = "?"
})
```

This can easily accommodate a richer API like the one in your branch @MarkusFreitag

**Comment by AlecAivazis** [comment]
Alright, since this issue is the only one left that's slated for this `v2` release, i'm going to go ahead and implement it so we can release this ASAP.

**Comment by AlecAivazis** [comment]
I just opened #222 which adds the ability to modify the `Format` of an `Icon` with the `WithIcons` option

**Comment by AlecAivazis** [comment]
This will be released in the upcoming `v2` that should be available by the end of the day
