### ISSUE TITLE
Add option to auto-select first value from filtering when enter is pressed

### ISSUE THREAD

**Issue by geocine** [AlecAivazis/survey#142]
I have this Question:
```Go
{
	Name:      "type",
	Validate:  survey.Required,
	Transform: GetResultString,
	Prompt: &survey.Select{
		Message: "Type of commit:",
		Options: []string{
			"feat     | new feature",
			"fix      | bug fix",
			"docs     | documentation",
			"style    | code formatting",
			"refactor | code refactor",
			"perf     | improve performance",
			"test     | add/update tests ",
			"chore    | other changes that doesn't modify src/test",
			"revert   | revert previous commit"},
		Default: "feat",
	},
}
```

The default is `feat`
```
? Type of commit:  [Use arrows to move, type to filter]
❯ feat     | new feature
  fix      | bug fix
  docs     | documentation
  style    | code formatting
  refactor | code refactor
  perf     | improve performance
  test     | add/update tests
```

Then I filter the options by typing 
```
? Type of commit: ch  [Use arrows to move, type to filter]
❯ chore    | other changes that doesn't modify src/test
```

Now if I press enter the value returned will still be `feat` unless I press the arrow keys. 
In this case it makes sense to just select `chore` since its the only result.

**Comment by AlecAivazis** [comment]
Hey @geocine - Thank you for reporting this and sorry for lagging on replying to you. I've been really busy with work.

I have yet to try to reproduce this but I wanted to assure you that I would look into it this weekend. It shouldn't be too much work to get this working so I suspect it will get fixed when I find some time to look into it.

**Comment by geocine** [comment]
Hi @AlecAivazis yes the default is set to `feat` here is the actual code https://github.com/geocine/golem

**Comment by AlecAivazis** [comment]
@geocine - this should now be fixed with #146. Mind taking a look?

**Comment by geocine** [comment]
@AlecAivazis  I can confirm it works 👍

**Comment by AlecAivazis** [comment]
@geocine - thanks!

**Comment by geocine** [comment]
@AlecAivazis - thank you this project, it is really useful. Will definitely let you know for issues I would encounter.
