### ISSUE TITLE
Split content of EDITOR variable on whitespace

### ISSUE THREAD

**Issue by nmiyake** [AlecAivazis/survey#147]
One of the users of an application that uses this library reported this issue:

```
Prompt [Enter to launch editor] Error: exec: "emacs -nw": executable file not found in $PATH
```

The issue is that their `EDITOR` variable is set to `emacs -nw` and `survey` currently uses the entire content of the variable as the executable name (https://github.com/AlecAivazis/survey/blob/master/editor.go#L156).

In shells like `bash`, line splitting is on by default so this "just works" in most cases.

This issue can be worked around by having people set their `EDITOR` variable to be a script that invokes the editor they want with the arguments that they want, but that can be a bit of a hassle. However, making this change in code here could be messy as well (determining exactly how to split on whitespace etc.).

Wanted to file this issue to see if others have encountered this or have feedback on it.

**Comment by AlecAivazis** [comment]
Thanks for reporting this @nmiyake - i haven't used the EditorPrompt much so I haven't run into it myself, but I think I understand what you're saying. I'll leave this open to collect feedback. Also @coryb  or @hinshun maybe have a good idea on ways we can support this. In the meantime, i'll reproduce the issue and see if I can think of a good solution

**Comment by hinshun** [comment]
Line splitting in bash is more complex than white space delimiting so in our projects we typically use [shellquote](https://github.com/kballard/go-shellquote).

**Comment by nmiyake** [comment]
Thanks for the fix! Do you know when you expect to tag the next release? I can depend on `master` for now, but would be great to have a tagged release with this fix!

**Comment by AlecAivazis** [comment]
@nmiyake i'm about to cut a release

**Comment by AlecAivazis** [comment]
This should be available in `v.1.6.2`

**Comment by nmiyake** [comment]
Confirmed -- thanks!
