### ISSUE TITLE
Add a message prompt feature

### ISSUE THREAD

**Issue by rmfish** [AlecAivazis/survey#160]
Add a info/warning message prompt without any answer.

**Comment by rmfish** [comment]
In my case, i use the survey ask one by one,  it always do something and send feedback between the asks. So i want  a message prompt without answer to display the feedback :)

**Comment by coryb** [comment]
I am not sure I understand your use-case, but prompts are just a Go interface.  You can provide your own implementation in your code.  If you don't want to re-render the prompt with the answer you could just implement a no-op `Cleanup` function:
```
type MyConfirm struct {
    Confirm
}

func (my *MyConfirm) Cleanup(val interface{}) error {
    return nil
}
```
