### ISSUE TITLE
Input type automatically converts the first letter of the input to uppercase

### ISSUE THREAD

**Issue by whimthen** [AlecAivazis/survey#164]
As the title says, I type 'loveparadise_l' and automatically change to 'Loveparadise_l'

![2018-11-27 16 29 45](https://user-images.githubusercontent.com/26761592/49068444-b9ef0900-f261-11e8-8863-6858612fb0cc.gif)

**Comment by orymate** [comment]
You forgot to add a code snippet for reproducing the issue.

I suppose, you copied this line from the example, which is responsible for transforming the input to Title Case.

```go
        Transform: survey.Title,
```

**Comment by whimthen** [comment]
Sorry, I did forget to add the code.
```go
func main() {

	answers := struct {
		Address string `survey:"address"`
		Env     string `survey:"environment"`
	}{}

	var qs = []*survey.Question{
		{
			Name:      "address",
			Prompt:    &survey.Input{Message: "What is the withdrawal address?"},
			Validate:  survey.Required,
			Transform: survey.Title,
		},
		{
			Name: "environment",
			Prompt: &survey.Select{
				Message: "Choose a environment:",
				Options: []string{"zbg"},
				Default: "zbg",
			},
		},
	}

	// perform the questions
	err := survey.Ask(qs, &answers)
	if err != nil {
		log.Println(errorP, err.Error(), end)
		return
	}
	fmt.Println(answers)
}
```
And I delete `Transform: survey.Title,` then is ok.
Thanks for your help.

**Comment by AlecAivazis** [comment]
I'm happy you were able to figure this out @whimthen! Thanks @orymate for helping out
