### ISSUE TITLE
Slow input when using SSH

### ISSUE THREAD

**Issue by crawford** [AlecAivazis/survey#170]
I haven't dug into this yet, but I've noticed that user input slows to a crawl when this library is used over SSH. I spun up `examples/simple.go` on a remote server (~150ms of network latency) and then pasted a large input (`base64 --wrap=0 < /dev/urandom | head --bytes=100 | xclip`) into the survey input. I watched as it took about 10 seconds to fully input my response.

**Comment by stbenjam** [comment]
It seems to happen regardless of using SSH or not, I see it locally.  I've narrowed down the problem to RuneReader reading the cursor's location after every character press, specifically, I think Location is the bottleneck:

https://github.com/AlecAivazis/survey/blob/master/terminal/cursor.go#L92

**Comment by stbenjam** [comment]
https://github.com/AlecAivazis/survey/pull/174
