### ISSUE TITLE
Go Test is suspended, when I send the string "R"

### ISSUE THREAD

**Issue by shlao** [AlecAivazis/survey#183]
Hi, I ran the test this morning and found that  after I modified the file, password_test.go, then the Test was suspended.  It is interesting...
$  git describe
No annotated tags can describe 'ee72c28b95a5ff3e227cfd403f556f0ef4b07ca5'.

$ git pull
Already up to date.

$ git log -1
commit ee72c28b95a5ff3e227cfd403f556f0ef4b07ca5 (HEAD -> master, tag: v1.8.2, origin/master, origin/HEAD)
Author: Jonathan Chappelow <chappjc@users.noreply.github.com>

$ go version
go version go1.10.4 linux/amd64

$ cat /etc/system-release
Fedora release 28 (Twenty Eight)
```
git diff 
diff --git a/password_test.go b/password_test.go
index 868fdfd..743240d 100644
--- a/password_test.go
+++ b/password_test.go
@@ -62,11 +62,11 @@ func TestPasswordPrompt(t *testing.T) {
                        },
                        func(c *expect.Console) {
                                c.ExpectString("Please type your password")
-                               c.Send("secret")
+                               c.Send("R")
                                c.SendLine("")
                                c.ExpectEOF()
                        },
-                       "secret",
+                       "R",
                },
                {
                        "Test Password prompt interaction with help",
```

It is suspended, as follows:
```
--- PASS: TestPasswordRender (0.00s)
=== RUN   TestPasswordPrompt
=== RUN   TestPasswordPrompt/Test_Password_prompt_interaction
=== PAUSE TestPasswordPrompt/Test_Password_prompt_interaction
=== RUN   TestPasswordPrompt/Test_Password_prompt_interaction_with_help
=== PAUSE TestPasswordPrompt/Test_Password_prompt_interaction_with_help
=== CONT  TestPasswordPrompt/Test_Password_prompt_interaction
=== CONT  TestPasswordPrompt/Test_Password_prompt_interaction_with_help
```

**Comment by AlecAivazis** [comment]
I'm going to close this and ask that we discuss this issue further in the `survey` channel on the gophers slack

**Comment by AlecAivazis** [comment]
I'm re-opening this as it turns out its a different issue than the known problem
