### ISSUE TITLE
Select and multiselect controls not obvious 

### ISSUE THREAD

**Issue by willdot** [AlecAivazis/survey#184]
When using the select or mutliselect options, the instructions are "Use arrows to move, type to filter" but it doesn't mention anything about what key to use to select an option or how to continue.

**Comment by jstrachan** [comment]
I hit this too - I've raised a PR for multi-select https://github.com/AlecAivazis/survey/pull/185

**Comment by AlecAivazis** [comment]
I'm going to close this since #185 and #187 have been merged
