### ISSUE TITLE
Dynamic Question Asking. Binary Tree

### ISSUE THREAD

**Issue by zanven42** [AlecAivazis/survey#188]
Hi i had forked this project some time ago and made some light modifications to enable some extra features mostly around being able to skip questions dynamically, so i could make a secondary package that handled composing these questions through yaml files in a way that was simple enough to expose to non programmers and allowed the people answering them to avoid massive blocks of questions that are not relevant.

fork: https://github.com/zanven42/survey

example question file:
https://gitlab.com/zanven/surveycompose/blob/master/example/survey.yml

I am wondering if both of these repositories / features is something you would like to see a PR for in the future as it was my original intention to try and pull these things back into this repo if possible.

**Comment by AlecAivazis** [comment]
Hey @zanven42 - thank you for wanting to contribute your changes back to this project! 

Both of these sound like very useful features for users. The second feature is something I have thought a lot about and have some ideas. A few people have asked, i'll try to find the issue with the best explanation of my view and we can move the conversation there. The first feature sounds really cool! However, I don't think it's something that `survey` should be responsible for. That feels like something that belongs "above" that wraps the various prompts and has opinions on what to do with the answers.

**Comment by AlecAivazis** [comment]
Here is the issue I had in mind: https://github.com/AlecAivazis/survey/issues/156
