### ISSUE TITLE
Make survey/core customizations per-question

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#192]
It looks like to change something like the ErrorIcon or QuestionIcon, I must do

    core.QuestionIcon = ...

This isn't great since it effects every part of my program globally, and might have side-effects that I can't easily find out.

I would've preferred more if the output customizations are per-question based, such as encapsulated in a `survey.AskOpts` implementation so that I can do.

```
survey.AskOne(&survey.Select{...}, &v, &survey.QuestionOpts{QuestionIcon: ...})
```

instead of setting a global variable.

**Comment by AlecAivazis** [comment]
I'm going to close this in favor of #201 where I am tracking all of the different places where this sort of refactor should happen. This work is currently being done in the `ask-opts` branch if you want to track it
