### ISSUE TITLE
Is it possible to get selectedIndex from Select?  If not, why not?

### ISSUE THREAD

**Issue by tony--** [AlecAivazis/survey#195]
First of all, thanks for sharing survey!  It's a big help for a project I am working on.
Second of all, I am new to golang, so I imagine I am constantly making things harder than necessary 😑 so please be gentle.

I am using Select to display a menu, then I want to take some additional action based on the the selection.  I am creating a slice of choices and a matching slice of actions.  As I add options/actions, the indexes match, so I want to get the selectedIndex from the Prompt passed to AskOne, but it's not exported.  

Of course I can just loop over the slice to find the index of the selected value, but it seems like it should be unnecessary to do this.

Please help me understand if there is a different option than looping over the slice.

**Comment by tony--** [comment]
I want to follow the instructions and add the Question label, but I cannot edit the Labels ☹️

**Comment by MarkusFreitag** [comment]
Hi Tony,
regarding your first question: 
As you correctly noticed, the `Select` component returns the chosen option instead of the index. Therefore I would recommend to transform your two separate slices into a map. The following is just an example how this could look like.
```golang
package main
  
import (
  "fmt"

  "gopkg.in/AlecAivazis/survey.v1"
)

func getKeys(m map[string]string) []string {
  keys := make([]string, 0, len(m))
  for key := range m {
    keys = append(keys, key)
  }
  return keys
}

func main() {
  actions := map[string]string{
    "get": "get action",
    "set": "set action",
    "list": "list action",
  }
  var choice string
  prompt := &survey.Select{
      Message: "Choose an action:",
      Options: getKeys(actions),
  }
  survey.AskOne(prompt, &choice, nil)
  fmt.Println(actions[choice])
}
```
Please do not hesitate to come back, in case you have further questions.

**Comment by MarkusFreitag** [comment]
> I want to follow the instructions and add the Question label, but I cannot edit the Labels

I'm sorry, I don't get what you mean. Could you please explain it a bit more detailed?

**Comment by tony--** [comment]
@MarkusFreitag I was referring to [the contributing guidelines for the project](https://github.com/AlecAivazis/survey/blob/master/CONTRIBUTING.md#getting-help).  It says 
> Please remember to tag the issue with the Question label so the maintainers can get to your question as soon as possible.
But I cannot add the Question label.

**Comment by MarkusFreitag** [comment]
Ah ok, I think this is a permission issue. Maybe @AlecAivazis can check the settings.

**Comment by AlecAivazis** [comment]
Oh whoops! Looks like GitHub does not allow non-collaborators to add labels - I'll remove that from the contributors guide.

Thanks for following up with this @MarkusFreitag and thanks for actually reading the contributor's guide @tony--!! I'm going to close this as it looks like you have a solution. Let us know if you run into anything else
