### ISSUE TITLE
Remove config via global variable

### ISSUE THREAD

**Issue by AlecAivazis** [AlecAivazis/survey#201]
Branching off of the conversation in #192, we should see if we can use variadic configuration functions to remove as much configuration via global variables as possible.

The things we should consider removing from global config:
- [x] Validators to `AskOne`
- [x] Icon Text
- [x] Help input rune
- [x] PageSize 
- [x] Default filter

**Comment by ahmetb** [comment]
+PageSize

**Comment by AlecAivazis** [comment]
@ahmetb thanks for the suggestion! I'm curious if that was because you think there is a better default? I pulled 7 out of nowhere so if you have any reason for a particular number, i'd love to hear it

**Comment by ahmetb** [comment]
I don't need a better default. :) I just need to configure it per-question.

**Comment by AlecAivazis** [comment]
Well you can already configure it per prompt by setting the `PageSize` field on the `Select` and `MultiSelect` structs but I'm adding the ability to set it with an `AskOpt` now
