### ISSUE TITLE
survey.Select accepts invalid response, returns empty string

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#205]
If I filter down options in survey.Select.Options by typing random stuff like asdfafdafsa and hit return, I get no error from the survey.AskOne.

It feels like when a choice is not made and the code exits, it should be returning an error so that I don't have to check for empty string.

Is this a valid assessment?

**Comment by AlecAivazis** [comment]
Hm I think the right behavior is not to accept the return if there are no options that are visible when the filter is applied. I don't think `AskOne` should check if there's a response unless you passed the `survey.Required` validator

**Comment by ahmetb** [comment]
This makes sense. Thanks.
