### ISSUE TITLE
Readme Example Import Path different

### ISSUE THREAD

**Issue by Wulfheart** [AlecAivazis/survey#224]
I think the import path shouldn't be `github.com/AlecAivazis/survey/v2` but `github.com/AlecAivazis/survey/`.

**Comment by Wulfheart** [comment]
Pardon me, it says that it is documenting the upcoming v2 release. Is there a release date planned and are default values supported?

**Comment by AlecAivazis** [comment]
Hey @Wulfheart! Sorry for the confusion.

There is no official release date, I've just been working on collecting a bunch of API breaking changes that I've been planning into one release so I can clean up some bits of the API that bother me. Once those are all in and we're confident that there aren't any we're going to regret not getting in, i'll release it.

The released version (linked in the docs at the end of that note) should have default values for all of the prompts. Are you seeing something different?

**Comment by AlecAivazis** [comment]
I'm going to close this since i'm not sure if there's an actual problem. Please let me know if there is and I"ll gladly reopen
