### ISSUE TITLE
unexpected module path 

### ISSUE THREAD

**Issue by ASVBPREAUBV** [AlecAivazis/survey#226]
I tried using survey in the playground.
https://play.golang.org/p/tVVi5q0zyjc
Loads the dependency but does not run it.

**Comment by AlecAivazis** [comment]
Hey @ASVBPREAUBV!

Well the first problem is the import path - you forgot the `v2` at the end. After fixing that I get another error that seems to be related to the architecture that the playground runs on. I'm going to close this as we haven't had any one complain yet and it's not very clear to me that the playground would ever support survey, I don't know how complete their terminal emulation is.
