### ISSUE TITLE
Add hierarchical prompt support

### ISSUE THREAD

**Issue by mijdavis2** [AlecAivazis/survey#23]
Would be great to see hierarchical prompt support as in inquirer with ```when``` object -- [inquirer/objects](https://github.com/sboudrias/Inquirer.js#objects). 

This was really nicely implemented in yeoman https://github.com/yeoman/generator/issues/278

**Comment by AlecAivazis** [comment]
@mijdavis2 i tried to capture this [here](https://github.com/AlecAivazis/survey/issues/5). Let me know if you have any ideas
