### ISSUE TITLE
Edit release notes for correct import path

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#230]
`github.com/alecaivazis/survey/v2` vs `AlecAivazis` actually is known to cause problems. When Sirupsen/logrus has changed from `github.com/Sirupsen/logrus` to `github.com/sirupsen/logrus` it actually broke a lot of things like various go dependency management tools.

Please make sure to use the correct capitalization in import paths.

**Comment by AlecAivazis** [comment]
Nice catch! Thanks

**Comment by ahmetb** [comment]
yeah it was totally failing when I used lowercase import

```
$ go mod tidy
go: finding github.com/alecaivazis/survey/v2/core latest
go: finding github.com/AlecAivazis/survey/v2/core latest
go: github.com/alecaivazis/survey/v2@v2.0.0: parsing go.mod: unexpected module path "github.com/AlecAivazis/survey/v2"
```

**Comment by AlecAivazis** [comment]
damn! Well luckily it wasn't a problem with the codebase...
