### ISSUE TITLE
v2: unselected options are bold, selected option normal formatted

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#231]
After migrating to v2, non-highlighted options are bold, focused option is non-bold. Seems unintuitive. Is this expected?

![image](https://user-images.githubusercontent.com/159209/60041080-526e3000-966f-11e9-97de-893f46c4f285.png)

**Comment by AlecAivazis** [comment]
Yea that definitely doesn't look right. Let me check

**Comment by AlecAivazis** [comment]
Huh, so apparently the v1 template was also bolding that text... Either way, I agree with you that it's not very pretty. I'll open a PR now

**Comment by ahmetb** [comment]
hmm I don't think this was happening in v1.

**Comment by AlecAivazis** [comment]
You can see the `hb` at the end of the line here: https://github.com/AlecAivazis/survey/blob/v1/select.go#L56

**Comment by ahmetb** [comment]
my bad. just checked 1.8.3, looks like it was making all options bold (incl. the focused one), so that's why I didn't notice it earlier.
