### ISSUE TITLE
v2: #219 regression: shows "space to select" for survey.Select

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#232]
Just upgraded to v2 and it looks like what we fixed in #219 has regressed.

I now see the `space to select` message again in `survey.Select` mode.

![image](https://user-images.githubusercontent.com/159209/60041487-69615200-9670-11e9-9b7c-34ed5956e393.png)

**Comment by AlecAivazis** [comment]
Gah!! another nice catch. Not sure how that snuck back... I'm opening a PR now with this and the other fixes
