### ISSUE TITLE
survey.Select to return custom type

### ISSUE THREAD

**Issue by dgkanatsios** [AlecAivazis/survey#238]
I would like to have survey.Select return a custom type, so I can assign it to my result struct. I thought I could use the Transform field to do that, but it seems that it expects me to return a `core.OptionAnswer` value. Is this correct? If it is, what's the point of having Transformer return `interface{}`? Thanks!

**Comment by AlecAivazis** [comment]
Hey @dgkanatsios - thanks for opening this issue. 

Please #105 for more context on the select API. In short, I know its not ideal but atm the API does not allow what you want. There is a lot of discussion around what the right API is and not a lot of movement so I decided to leave things as they are today.

**Comment by luisdavim** [comment]
I have the same use case :(
