### ISSUE TITLE
Cleanup output for linux

### ISSUE THREAD

**Issue by mijdavis2** [AlecAivazis/survey#24]
Testing the same shells, prompt themes, etc, I get clean output on OSX but extra color codes on linux (ubuntu/debian).

Examples:
<img width="487" alt="screen shot 2017-01-18 at 4 14 34 pm" src="https://cloud.githubusercontent.com/assets/10160872/22088992/0116e6a8-dd9d-11e6-9d57-e3ca1b05a096.png">

<img width="333" alt="screen shot 2017-01-18 at 4 21 23 pm" src="https://cloud.githubusercontent.com/assets/10160872/22088983/e8cf1728-dd9c-11e6-985e-f446550a187d.png">

This might just be an issue with buger/goterm itself. [This issue](https://github.com/buger/goterm/issues/9) suggests color code issues could possibly be mitigated with https://github.com/fatih/color.

**Comment by AlecAivazis** [comment]
Hey @mijdavis2 sorry for not responding earlier. I keep getting distracted trying to think of what the problem could be. I have run `simple.go` on linux terminals many times without issues - can you give me a quick summary of the terminal, os, etc?

**Comment by AlecAivazis** [comment]
@mijdavis2 is this still the case? I've recently changed the way the output gets rendered to the terminal so it might be fixed.

**Comment by mijdavis2** [comment]
Looks like it's fixed! Thanks!

**Comment by AlecAivazis** [comment]
Awesome, thanks for reporting it
