### ISSUE TITLE
Typo of a function signature in Readme

### ISSUE THREAD

**Issue by Manawasp** [AlecAivazis/survey#244]
Hello,

Just to let you know there is a small typo in the example from the README.md.
Line 261:

```golang
func myFilter(filterValue string, optValue string, optIndex int) include bool {
    // only include the option if it includes the filter and has length greater than 5
    return strings.Contains(optValue, filterValue) && len(optValue) >= 5
}

// configure it for a specific prompt
&Select{
    Message: "Choose a color:",
    Options: []string{"red", "blue", "green"},
    Filter: myFilter,
}

// or define a default for all of the questions
survey.AskOne(prompt, &color, survey.WithFilter(myFilter))
```

The function signature should be `...) bool {` not `...) include bool {`

Thanks again for your work!

**Comment by AlecAivazis** [comment]
Whoops!! Good catch. 

I am away from my computer for a few days but if you wanted to open a PR with that change, I can easily review it from my phone and get it merged. Otherwise I’ll try to remember to fix it when I get back.
