### ISSUE TITLE
Conditional prompt

### ISSUE THREAD

**Issue by brpaz** [AlecAivazis/survey#252]
Hello. Its possible to define a conditional prompt, meaning that it will only appear based on the answer on some other prompt? 

Thank you

**Comment by MarkusFreitag** [comment]
You can achieve this behaviour by using two `AskOne`s after each other.
Do the first one, valid its response and then decide whether to also do the second one.

**Comment by AlecAivazis** [comment]
I'm going to close this since its gone stale. Thanks for helping out as always @MarkusFreitag
