### ISSUE TITLE
Cannot vendor 2.0.x

### ISSUE THREAD

**Issue by WalkerGriggs** [AlecAivazis/survey#256]
Trying to vendor Survey with `dep ensure --add github.com/AlecAivazis/survey@2.0.4` yields the message

```
v2.0.4: "github.com/AlecAivazis/survey" imports "github.com/AlecAivazis/survey/v2/core", which contains malformed code: no package exists at "github.com/AlecAivazis/survey/v2/core"
```

dep version: devel on 1.12.8
go version: 1.13.1

**Comment by AlecAivazis** [comment]
Hey @WalkerGriggs!

Sorry to hear you are running into problems with `dep`. A few people have brought this up and it seems to be a `dep` issue since they don't support gomodules. Sorry I can't be of much help!
