### ISSUE TITLE
Preselection of multiSelect

### ISSUE THREAD

**Issue by MeisterTea** [AlecAivazis/survey#259]
Is it possible to give an array of selected items to survey ?
Is it supposed to be shown as checked item ?

**Comment by AlecAivazis** [comment]
1) Unforunately not. This has been a long running discussion among the survey maintainers and its not clear the right API to support this. For more information you can see #105. I know this isn't the answer you wanted but for now its the best I can provide at the moment.
2) You can change the icon set by following [these instructions](https://github.com/AlecAivazis/survey#changing-the-icons).

**Comment by ChristianHuff-DEV** [comment]
@AlecAivazis is there a way to keep the selected items if the validation returns an error?

Currently when my validation fails even previously selected items are back to being not selected.
