### ISSUE TITLE
Multiple select duplicates question (with .gif)

### ISSUE THREAD

**Issue by rafamrs** [AlecAivazis/survey#266]
![](https://i.imgur.com/LaYKlTz.gif)

I noticed for some reason MultipleSelect duplicates the questions when using the arrows, as the GIF above shows it. But as far as I noticed, is just a OSX problem, on Windows 10 was working ok.

**Comment by AlecAivazis** [comment]
hey @rafamrs I'm sorry you're running into this bug.

I'm curious if your terminal width is thinner than the prompt? If so, this is a known bug (#101)

**Comment by rafamrs** [comment]
Yes it is, I tested with a larger on and it worked ok :)
