### ISSUE TITLE
Let the filter stay active unless deleted

### ISSUE THREAD

**Issue by siredmar** [AlecAivazis/survey#277]
Hi! 
Currently i am using a MultiSelect with some filter. I've written my own Filter function. Pretty much is working pretty well, but:
Is it possible to let the typed in filter string be active unless deleted by the user?

Scenario: Selecting some of the elements in a MultiSelect that match the input filter
Currently this does not work: The user types the filter, selects one element and the filter setting is gone. The user has to type in the same filter again.

**Comment by siredmar** [comment]
See PR #278

**Comment by AlecAivazis** [comment]
I'm closing this since your PR has been merged. Thanks again!
