### ISSUE TITLE
github.com/AlecAivazis/survey/go.mod at revision v1.4.1: unknown revision v1.4.1

### ISSUE THREAD

**Issue by devinacosta** [AlecAivazis/survey#285]
I am trying to build Sensu Go to get it included in EPEL repo. However when I am running the build on Koji (Red Hat's build system) I am getting error below. What i don't understand is if i build it on my system using the same Go Version i don't get the error?

go: github.com/AlecAivazis/survey@v1.4.1: reading github.com/AlecAivazis/survey/go.mod at revision v1.4.1: unknown revision v1.4.1
go: github.com/AlecAivazis/survey@v1.4.1: reading github.com/AlecAivazis/survey/go.mod at revision v1.4.1: unknown revision v1.4.1
go: github.com/AlecAivazis/survey@v1.4.1: reading github.com/AlecAivazis/survey/go.mod at revision v1.4.1: unknown revision v1.4.1
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.Vsa1t3 (%build)
    Bad exit status from /var/tmp/rpm-tmp.Vsa1t3 (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 746, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/sensu-go.spec

**Comment by miralgj** [comment]
I was able to get around this by setting the `GOPROXY` environment variable.

`export GOPROXY="https://proxy.golang.org,direct"`

**Comment by AlecAivazis** [comment]
Thank you for the input @miralgj 

Is this still a problem @devinacosta?
