### ISSUE TITLE
Allow questions to set defaults from previously answered questions in the same set of questions

### ISSUE THREAD

**Issue by rdmulford** [AlecAivazis/survey#286]
When defining multiple questions in one block, it would be great if you could set the default value for one question equal to the answer of a previously answered question. See example below for more clarity on the issue.

## Environments Tested
OS: MacOS
Terminal: iTerm2
Shell: zsh
Version: github.com/AlecAivazis/survey/v2 v2.0.7

## Example Program:
```
package main

import (
    "github.com/AlecAivazis/survey/v2"
)

type Answers struct {
    Text      string
    Default   string
}

func main() {
    answers := Answers{}
    var questions = []*survey.Question{
        {
            Name:     "Default",
            Prompt:   &survey.Input{Message: "Enter text"},
            Validate: survey.Required,
        },
        {
            Name:     "Default",
            Prompt:   &survey.Input{
                Message: "Enter text (should be default here)",
                Default: answers.Default,
            },
            Validate: survey.Required,
        },
    }
    if err := survey.Ask(questions, &answers); err != nil {
        panic(err)
    }
}
```

## Output
<img width="321" alt="Screen Shot 2020-04-02 at 2 00 17 PM" src="https://user-images.githubusercontent.com/14285693/78291219-a1909d80-74ea-11ea-9891-0f71d563a336.png">

## Expected
I would expect the second question to display a default value of `text`.

**Comment by kke** [comment]
I think if `answers` already has a valid value for the key, it should be skipped.

**Comment by infixint943** [comment]
> I think if `answers` already has a valid value for the key, asking for one should be skipped.

Define _valid_ value. `nil`, `0`, `""` are all _valid_ values in golang.

**Comment by joerodrig** [comment]
I stumbled across this case earlier when working on a CLI that I wanted to have some power user flags. For example, something like: `./cli create --name MyInput` could help with cases where you would normally be prompted to enter a name.

My immediate thought was maybe adding a check [before the prompt](https://github.com/AlecAivazis/survey/blob/master/survey.go#L291) that checks if there's already an answer for the question, and if that answer passes validations, to skip the prompt portion. But then I can see how that opens up a whole other class of questions -- ie. How does a validation failure look? What if you just want pre-filled answers to be suggested defaults? What if you want them to skip validations?

Ultimately, it felt like I was trying to shoehorn my own business logic into the package, so I ended up managing those inputs on my end.

Simple Example:

```go
var name string

func main() {
    ...
    if len(name) > 0 {
        fmt.Println(fmt.Sprintf("Name: %s", name))
        answers.Name = name
	...
    } else {
        // questionsWithoutName is the array of survey.Question structs, with the Name question filtered out
	err := survey.Ask(questionsWithoutName, &answers)
	...
    }
}
```

If you're running validations or transformations, things are likely a bit more complicated, but I was just working on something tiny, so this worked well enough.

**Comment by montanaflynn** [comment]
I also want to use a default and suggestions based on previous answers. 

This would be very welcome, the syntax suggested seems reasonable.

**Comment by mislav** [comment]
Thanks everyone for the suggestions!

If your application needs subsequent questions to react to the answers of previous questions, you should go with multiple Asks:
```go
if err := survey.Ask(questions1, &answers); err != nil {
  panic(err)
}
if err := survey.Ask(questions2, &answers); err != nil {
  panic(err)
}
```
That way you have absolute freedom to implement whichever logic you'd like.

Note that the `Default` property of Survey inputs is a Go value, not a reference. The provided value will be static and cannot change dynamically between survey prompts.
