### ISSUE TITLE
How to get input from another reader (or *file) instead of os.Stdin?

### ISSUE THREAD

**Issue by Prnyself** [AlecAivazis/survey#287]
I want to test my code and inject the input from another file for mocking input in `os.Stdin`, and I tried to replace `os.Stdin` with a tempfile or use `survey.WithStdio` to inject the tempfile, but neither worked. 
Looks like [this](https://github.com/AlecAivazis/survey/blob/master/terminal/runereader.go#L45) buffer turned into all-zero-bytes-slice, so that `rr.ReadRune()` cannot read rune from `stdio.In` and just return an `EOF` error.
So how can I get input from another file?

**Comment by viniciusramosdefaria** [comment]
We are facing the same problem, seems like when trying to read runes something unexpected happened. @Prnyself this problem was solved with a turnaround implementation?

**Comment by Prnyself** [comment]
> We are facing the same problem, seems like when trying to read runes something unexpected happened. @Prnyself this problem was solved with a turnaround implementation?

Still not figure out. sigh

**Comment by viniciusramosdefaria** [comment]
@Prnyself i figured it out. The following snippet may help you:

```
func terminalRunner() {
	bufOut := new(bytes.Buffer)
	c, err := expect.NewConsole(expect.WithStdout(bufOut))
	if err != nil {
		fmt.Println(err)
	}
	defer c.Close()

	cmd := exec.Command("rit", "scaffold", "generate", "coffee-go")

	cmd.Stdin = c.Tty()
	cmd.Stdout = c.Tty()

	go func() {
		c.ExpectEOF()
	}()

	testCases := []testCase{
		{input: "test", expectOut: ".*Type your name.*"},
		{input: "es", expectOut: ".*Pick your coffee.*"},
		{input: "", expectOut: ".*Delivery.*"},
	}

	go func() {
		for i := 0; i < len(testCases); i++ {
			for {
				matched, _ := regexp.MatchString(testCases[i].expectOut, bufOut.String())
				if matched {
					c.SendLine(testCases[i].input)
					break
				}
				time.Sleep(1 * time.Second)
			}
		}
	}()

	cmd.Start()
	cmd.Wait()

	fmt.Println(bufOut.String())
}
```

**Comment by Prnyself** [comment]
cool, that looks similar with input manually. 
By the way, the package `expect` indicates [go-expect](https://github.com/Netflix/go-expect) ?

**Comment by viniciusramosdefaria** [comment]
Yes, it is. Ops, I missed the import section, here it goes:
```
import (
    "bytes"
    "fmt"
    "github.com/Netflix/go-expect"
    "os/exec"
    "regexp"
    "time"
)
```

**Comment by Prnyself** [comment]
Thank you for your help!
Let's just leave this open, and see whether the maintainer would raise any native-project features for this.

**Comment by Prnyself** [comment]
I just found that tips about testing are already in [**Readme**](https://github.com/AlecAivazis/survey#testing) and I missed it.
So anyone has the same issue about testing, just try to use `go-expect` with `virtual terminal` as mentioned :).
