### ISSUE TITLE
How to default a confirmation?

### ISSUE THREAD

**Issue by richardltc** [AlecAivazis/survey#294]
Is there a way that we can default a confirmation to either true or false?

Thanks

**Comment by MarkusFreitag** [comment]
Yes, you can set the default when creating a `survey.Confirm` component like this:
```
  var answer bool
  prompt := &survey.Confirm{
    Message: "Do you like cookies?",
    Default: true, // default to true/yes because who doesn't like them
  }
  survey.AskOne(prompt, &answer)

**Comment by infixint943** [comment]
Close this since its solved? @richardltc

**Comment by richardltc** [comment]
Yes please. All sorted now.

Thanks

**Comment by richardltc** [comment]
Thank you, and sorry for they *very* later reply.

Richard
