### ISSUE TITLE
Suggestion: Let Ctrl+j/k to navigate up and down in Multiline Question

### ISSUE THREAD

**Issue by wanecek** [AlecAivazis/survey#297]
## What

When prompted with e.g. a MultilineQuestion, I would love it if `Ctrl+j`/`Ctrl+k` mapped to ArrowUp and ArrowDown respectively.

## Why

This would accommodate for users who prefer vim(-like) keybindings. As far as I can tell, this would'nt interfere with normal usage of the library.

One example of another projects using this keybinding is [junegunn/fzf](https://github.com/junegunn/fzf/blob/dda3e3c39a9b903fab3754a7a39a7946a2dd836f/README.md#using-the-finder).

I realize this may be slightly niched, and fully understand if this just falls under the category feature-creep. It may also be better solved on the users' side, e.g. by having the terminal emulator do the mapping. Thoughts?

**Comment by AlecAivazis** [comment]
hey @wanecek currently the user can enter/exit vim mode by pressing the escape key. Does that work for you? I'm not sure having two separate keyboard-based navigation schemes is worth the extra complexity

**Comment by wanecek** [comment]
Huh. I had no idea, thank you very much for clarifying. That should accommodate my use-case, thank you. Now that you mentioned it, I even found it written out in the README :facepalm:.

Thanks for taking your time to reply, I'll close this issue.

**Comment by AlecAivazis** [comment]
Awesome! Glad to hear that works. Let me know if you run into any more issues!

**Comment by niksingh710** [comment]
> hey @wanecek currently the user can enter/exit vim mode by pressing the escape key. Does that work for you? I'm not sure having two separate keyboard-based navigation schemes is worth the extra complexity

That's awesome but is there any way so that I can map any other key to work as esc
e.g quickly pressing `jk` as esc as it matches the vim config and doesn't break my flow?
