### ISSUE TITLE
Put cursor on selected line

### ISSUE THREAD

**Issue by shindere** [AlecAivazis/survey#305]
This issue stems from a discussion started at

https://github.com/cli/cli/issues/1085

and in particular comment

https://github.com/cli/cli/issues/1085#issuecomment-705164274

Would it please be possible to patch the library so that the cursor gets
placed on the selected line? It would make it more usable from a braille
display which generally follows the cursor.

**Comment by AlecAivazis** [comment]
Absolutely! Thank you so much for bringing this up. I had NO idea that's all it took to work better with braille displays.

**Comment by shindere** [comment]
Alec Aivazis (2020/11/02 13:31 -0800):
> Absolutely! Thank you so much for bringing this up. I had NO idea
> that's all it took to work better with braille displays.

Many thanks for your positive feedback!

This kind of knowledge is indeed not very widespread.

If you implement the feature and need testing, please feel free to
contact me either here or by e-mail directly:
Sebastien.Hinderer@inria.fr

Thanks!

**Comment by vilmibm** [comment]
@AlecAivazis Hiya!

I'm hoping to take on this work on behalf of the GitHub CLI team; let me know if there are pitfalls or other issues I should be aware of before I dig it.

**Comment by AlecAivazis** [comment]
Awesome!! I’m super excited to hear that @vilmibm. Nothing specific comes to mind but please let me know if you need any guidance.
