### ISSUE TITLE
Typing into prompt clears previous lines in terminal

### ISSUE THREAD

**Issue by benpleitner** [AlecAivazis/survey#318]
**What operating system and terminal are you using?**
MacOS Catalina / iTerm. Saw this on MacOS High Sierra as well.

**An example that showcases the bug.**
I've attached a video of the bug in this zip file: [BugDemo.zip](https://github.com/AlecAivazis/survey/files/5619166/BugDemo.zip)

It seems that when I adjust the width of my terminal tab so that the prompt text is all the way at the end of the terminal screen (i.e. no whitespace between the last character in the prompt description text - ":" in this case -  and the end of the terminal screen), a line in my terminal is cleared every time I type a character.

**What did you expect to see?**
I would expect my terminal to remain as is when I type input into a prompt.

**What did you see instead?**
I saw my terminal clear when I typed given the specifications above.

**Comment by AlecAivazis** [comment]
This should now be fixed in `v2.2.7`
