### ISSUE TITLE
New OnInterrupt behavior causes crash on Ctrl-C with default settings

### ISSUE THREAD

**Issue by mislav** [AlecAivazis/survey#319]
**What operating system and terminal are you using?** irrelevant

**An example that showcases the bug.** `go run examples/inputfilesuggestion.go` & press <kbd>Ctrl-C</kbd>

**What did you expect to see?** "interrupt" being printed and program exits

**What did you see instead?** crash on this line: https://github.com/AlecAivazis/survey/blob/f45c05b5039ca1f9c9c562be232f1c4044e0add0/survey.go#L311-L312

This is a regression in v2.2.5 due to the new OnInterrupt feature #301.

@AlecAivazis Why did a new, poorly argued for, backwards-incompatible feature ship in a patch release? Can we expect more functional changes like this in the v2.2.x line?

Would you consider branching off something like a `release-2.2` branch, reverting #301 there, and backporting to it only bug fixes going forward so that we can be sure that new tags on the v2.2.x patch line do _not_ also bundle new features?

**Comment by AlecAivazis** [comment]
hey @mislav - i'm sorry that this slipped by. I wish i had a better excuse but I have been very busy lately and did not have a lot of time to look over this change. I agree that it was an inappropriate change to add to a patch release, especially considering there was a bug.

**Comment by AlecAivazis** [comment]
I"m going to close this since I reverted #301 and don't think it will be merged back in. Thanks for the honest reaction @mislav, kind of shocked me into thinking more clearly about the change <3
