### ISSUE TITLE
Multiline input: weird cursor placement

### ISSUE THREAD

**Issue by noerw** [AlecAivazis/survey#324]
**What operating system and terminal are you using?**
fedora linux, gnome terminal

**An example that showcases the bug.**
any multiline input

**What did you expect to see?**
Have the cursor on the next (free) line

**What did you see instead?**
Cursor initially hangs at the end of the prompt (eg `? Multiline: [Enter 2 empty lines to finish]<CURSOR>`)
I'm not sure this is intended (I see that in recent versions, the cursor remains indented for the following lines), but i think it looks much cleaner to have the input start on the next line.

![grafik](https://user-images.githubusercontent.com/7880552/102685962-37389e00-41dc-11eb-8689-ef9b08853c72.png)

**Comment by AlecAivazis** [comment]
Hey @noerw! Thanks for reporting this.

I agree the current cursor placement isn't ideal however I think the correct behavior is described in #305 which aims to align with screenreader's expected behavior. I'm going to close this ticket to keep things tidy but feel free to share your thoughts there
