### ISSUE TITLE
Take UnmarshalText into account when writing answer

### ISSUE THREAD

**Issue by florisvdg** [AlecAivazis/survey#332]
It would be nice for [`core.WriteAnswer`](https://github.com/AlecAivazis/survey/blob/dbdb3e56a5e332b0478e0a8e8522e53a49fb7dcd/core/write.go#L35) to take [`UnmarshalText`](https://golang.org/pkg/encoding/#TextUnmarshaler) into account.

One of my survey questions maps its answer to a struct field:

```go
type Answers struct {
  Field SomeOtherStruct
}

func (s *SomeOtherStruct) UnmarshalText(data []byte) error {
   // code to convert text into struct
}
```

When using this struct as the survey output, it results in: `Unable to convert from string to type struct`.

But this conversion is already described in detail in my `UnmarshalText` function, which gets ignored now.
It would be nice if the conversion code would check if a type implements `TextUnmarshaler`.

**Comment by AlecAivazis** [comment]
Hey @florisvdg - survey already supports marshaling/unmarshaling outof custom types as described [here](https://github.com/AlecAivazis/survey#custom-types) in the docs. 

I'm going to close this to clean things up a bit but i will reopen if necessary
