### ISSUE TITLE
How to use MultiSelectTemplateData?

### ISSUE THREAD

**Issue by zlesnr** [AlecAivazis/survey#333]
I'd like to modify the config to allow custom runes for the selected bits.  The template looks like it just references the config, but I'm not clear how I modify the config.  I'm looking at the following.

```Golang
	prompt := &survey.MultiSelect{
		Message: msg,
		Options: options,
	}
```

Any pointers on how to modify the config here to allow the rendered template to look a little different?

**Comment by AlecAivazis** [comment]
Hey @zlesnr!

There is an explanation for changing the icons [here](https://github.com/AlecAivazis/survey#changing-the-icons) in the document. please let me know if that's not enough.

Cheers!
