### ISSUE TITLE
Cursor is sometimes not going back to the start of the line

### ISSUE THREAD

**Issue by PierreBtz** [AlecAivazis/survey#334]
**What operating system and terminal are you using?**

macOS Big Sur 11.0.1 with iterm2

**An example that showcases the bug.**

```
package main

import (
	"fmt"
	"github.com/AlecAivazis/survey/v2"
)

func main() {
	prompt := &survey.Password{
		Message: "password",
	}
	var pass string
	_ = survey.AskOne(prompt, &pass)

	fmt.Print("hello")
}
```

When running this sample, one can see that after the prompt the cursor stays aligned with the previous prompt text:

![Screenshot 2021-02-12 at 16 10 10](https://user-images.githubusercontent.com/9881659/107785436-deedca80-6d4c-11eb-9724-cc9617ec2993.png)

**What did you expect to see?**

The cursor is going back to the beginning of the line.

I tracked the issue to PR #309. I re-ran the previous test by adding a call to `c.HorizontalAbsolute(0)` (like it's done for Windows) and confirmed this was fixing my issue.

**Comment by davidji99** [comment]
I'm experiencing the same sort of issue where multiple outputs creates a staircase effect as mentioned by the OP.

**Comment by AlecAivazis** [comment]
@PierreBtz  - do you mind opening a PR with your fix? I would like to give it a shot but I dont have a lot of time at the moment

**Comment by PierreBtz** [comment]
@AlecAivazis I opened #335
