### ISSUE TITLE
How do I show help for a multiline input?

### ISSUE THREAD

**Issue by craicoverflow** [AlecAivazis/survey#349]
I am not able to show the help text when using a multiline input - but it works fine for other types.

Sample code:
```go
package main

import (
	"os"

	"github.com/AlecAivazis/survey/v2"
)

func main() {

	var description string

	descPrompt := &survey.Multiline{
		Message: "Description",
		Help:    "Valid characters are: a, b, c",
	}

	err := survey.AskOne(descPrompt, &description)
	if err != nil {
		os.Exit(1)
	}
}
```

Sample input:

```shell
❯ go run testdir/test.go
? Description [Enter 2 empty lines to finish]
```

Am I doing something wrong, or is there a bug?

**Comment by AlecAivazis** [comment]
Hey @chiaretto - thanks for opening this issue. Unforunately multiline inputs do not have support for the help text at the moment, you  can see more information on this here: https://github.com/AlecAivazis/survey/issues/236.

I'm going to close this issue to keep things tidy, feel free to contribute on that issue :)

**Comment by fabianofernandeszup** [comment]
Hi @AlecAivazis , I think you marked me by mistake on this issue.
