### ISSUE TITLE
expected support for linux idioms such as grep and yes

### ISSUE THREAD

**Issue by sstarcher** [AlecAivazis/survey#363]
**What operating system and terminal are you using?**
osx, iterm2

**An example that showcases the bug.**
* Create a prompt and run it on the command line.
* go run .  | grep 12.11
* yes | go run .

**What did you expect to see?**
* I would expect to still see the prompt.
* I would also expect the prompt to respond to keypresses
* Expected support for piping yes into the command, but instead a yes/no prompt would consider it an error

**Comment by noerw** [comment]
see also #328

**Comment by mislav** [comment]
Duplicate of https://github.com/AlecAivazis/survey/issues/328.

Currently it's only possible to use Survey when both stdin and stdout are connected to a terminal.
