### ISSUE TITLE
go get problem: module declares its path as: gopkg.in/AlecAivazis/survey.v1 but was required as: github.com/AlecAivazis/survey

### ISSUE THREAD

**Issue by quiquelhappy** [AlecAivazis/survey#369]
**What operating system and terminal are you using?**
tested on both MacOS Big Sur and ubuntu-latest (github actions)

**An example that showcases the bug.**
executing `go get github.com/AlecAivazis/survey`

**What did you expect to see?**
actual install

**What did you see instead?**
```
quiqueosunagarcia@MBP-de-Quique cli % go get github.com/AlecAivazis/survey
go get: github.com/AlecAivazis/survey@v1.8.1 updating to
        github.com/AlecAivazis/survey@v1.8.8: parsing go.mod:
        module declares its path as: gopkg.in/AlecAivazis/survey.v1
                but was required as: github.com/AlecAivazis/survey
```

**Comment by mislav** [comment]
Per https://github.com/AlecAivazis/survey/blob/v1/README.md the official import path is:
```
"gopkg.in/AlecAivazis/survey.v1"
```
