### ISSUE TITLE
panic: runtime error: slice bounds out of range [308:282]

### ISSUE THREAD

**Issue by bheeshamsre** [AlecAivazis/survey#383]
**What operating system and terminal are you using?**
5.10.16.3-microsoft-standard-WSL2
Ubuntu 20.04 LTS

**An example that showcases the bug.**

panic: runtime error: slice bounds out of range [308:282]

goroutine 1 [running]:
github.com/aulanov/go%2edbus.sessionBusPlatform(0xb2ea42, 0x18, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn_other.go:26 +0x1e9
github.com/aulanov/go%2edbus.SessionBusPrivate(0xd0, 0xac3020, 0x32d41f7f5266a301)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:99 +0xa7
github.com/aulanov/go%2edbus.SessionBus(0x0, 0x0, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:76 +0xae
github.com/99designs/keyring.init.1()
        /Users/markw/Code/go/pkg/mod/github.com/99designs/keyring@v0.0.0-20190110203331-82da6802f65f/kwallet.go:18 +0x26

**What did you expect to see?**
it should run the command

**What did you see instead?**
panic: runtime error: slice bounds out of range [308:282]

goroutine 1 [running]:
github.com/aulanov/go%2edbus.sessionBusPlatform(0xb2ea42, 0x18, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn_other.go:26 +0x1e9
github.com/aulanov/go%2edbus.SessionBusPrivate(0xd0, 0xac3020, 0x32d41f7f5266a301)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:99 +0xa7
github.com/aulanov/go%2edbus.SessionBus(0x0, 0x0, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:76 +0xae
github.com/99designs/keyring.init.1()
        /Users/markw/Code/go/pkg/mod/github.com/99designs/keyring@v0.0.0-20190110203331-82da6802f65f/kwallet.go:18 +0x26

**Comment by mislav** [comment]
The panic seems to come from `github.com/aulanov/go.dbus`. Why do you think it's a bug of the Survey libary?

**Comment by bheeshamsre** [comment]
Well, I want saml2aws working on my Ubuntu machine. I am not sure where the issue is. If this doesn't work for me, and giving panic error it must be a bug.

**Comment by bheeshamsre** [comment]
This is resolved
