### ISSUE TITLE
Password input without revealing password length

### ISSUE THREAD

**Issue by quiquelhappy** [AlecAivazis/survey#386]
Hello,
I'd link to render "", instead of "*" for the password input: similar to what linux does with pretty much every password input (aka invisible password input)

**Comment by AlecAivazis** [comment]
This can now be accomplished by setting the `HideCharacter` to a [zero-width space](https://zerowidthspace.me/)

**Comment by szh** [comment]
I tried this today and the cursor moves ahead which still reveals the password length.

**Comment by szh** [comment]
OK. I'll submit a PR for this.
