### ISSUE TITLE
How to (auto) trim typed text?

### ISSUE THREAD

**Issue by baxyz** [AlecAivazis/survey#399]
After reading the docs, I didn't find any clue to trim the text typed by the user.

Am I missing something?
Is there a workaround to do that?

For now, a space character is considered as a valid input for validators (`Required`, `MinLength(1)`, ...)

**Comment by mislav** [comment]
A validator will enforce a certain format of value, causing the prompt to be rendered again each time a validator fails. A "transformer" (see `Question.Transform` field) will post-process the value entered. You can define a transformer that will clean up leading or trailing whitespace so you don't end up with those characters.

**Comment by baxyz** [comment]
Thanks, that's work lovely with a custom `Required` validator and a simple Transform.
