### ISSUE TITLE
Disable MultiSelect answer output

### ISSUE THREAD

**Issue by browningluke** [AlecAivazis/survey#407]
Hi there, I was wondering if there was a way to disable the confirmation of selected answers.

Using [this example](https://github.com/AlecAivazis/survey/blob/master/examples/longmulti.go), if you were to select all of them, you'd end up with this:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/24992944/152670493-0e18a9ae-ebc9-45f9-bdac-112bbf550ea0.png">

I have a use case where I would need to select all (sometimes) from a very long list, so having it print all of the responses like that wouldn't work.

Any advice would be much appreciated!

**Comment by mislav** [comment]
Good point! I don't think there is a built-in way of disabling this, but you could override this template string from your app and take out the `ShowAnswer` line: https://github.com/AlecAivazis/survey/blob/3cabaff974060c555ea7d792abbd8272096fa919/select.go#L60

So, in your app:
```go
survey.SelectQuestionTemplate = `...`
```
