### ISSUE TITLE
Option to add comment/description on select option

### ISSUE THREAD

**Issue by luanraithz** [AlecAivazis/survey#416]
I created a [fork](https://github.com/luanraithz/survey) adding a option to show a description for a given select's option.

You can see how it looks [here](https://github.com/luanraithz/lvb)

If you guys are interested on that, tell me so I give a refact and open a pull request.

Cheers!

**Comment by AlecAivazis** [comment]
Hey @luanraithz! I think it looks like a very interesting addition - thanks for offering to submit a PR. I'd gladly take a look 👍

**Comment by mislav** [comment]
Thank you! https://github.com/AlecAivazis/survey/commit/c2be27f4a7faa58a920ea402d0984647a5b8deb2
