### ISSUE TITLE
Highlight items in Multiselect

### ISSUE THREAD

**Issue by 1F987** [AlecAivazis/survey#424]
Hi,
It can be hard to match a long string with the associated checkbox in the multi-select function, especially when just the end of the string differs. And it's more difficult when there is more than 7 items (default).
It could be a nice feature to highlight or apply a different color on the current line, but I didn't find a way to do this in the README. 

Current behavior with default (7 items): 

![Sélection_001](https://user-images.githubusercontent.com/76665233/169026556-4e5adfba-31b7-4383-a66e-e6bef339f1d1.png)

This could be nice : 

![Sélection_002](https://user-images.githubusercontent.com/76665233/169026575-0281573d-ef09-4098-9f6e-7833788c40db.png)

Thanks !

**Comment by mislav** [comment]
Hi, you can accomplish this by overriding this template string in Survey with your own: https://github.com/AlecAivazis/survey/blob/c2be27f4a7faa58a920ea402d0984647a5b8deb2/multiselect.go#L62-L79

So in your app, you can do something like:
```go
import github.com/AlecAivazis/survey/v2

func init() {
  survey.MultiSelectQuestionTemplate = `...`
}
```
