### ISSUE TITLE
Adding further questions after a select is breaking the package.

### ISSUE THREAD

**Issue by rv-cpavlick** [AlecAivazis/survey#43]
Putting further questions after a select question does not operate properly.

I will include a slightly modified version of your example/simple.go, where all I did was switch the order of the questions, so you can run it and see:

```golang
package main

import (
	"fmt"

	"github.com/AlecAivazis/survey"
)

// the questions to ask
var simpleQs = []*survey.Question{
	{
		Name: "color",
		Prompt: &survey.Select{
			Message: "Choose a color:",
			Options: []string{"red", "blue", "green"},
		},
		Validate: survey.Required,
	},
	{
		Name: "name",
		Prompt: &survey.Input{
			Message: "What is your name?",
		},
		Validate: survey.Required,
	},
}

func main() {
	answers := struct {
		Color string
		Name  string
	}{}
	// ask the question
	err := survey.Ask(simpleQs, &answers)

	if err != nil {
		fmt.Println(err.Error())
		return
	}
	// print the answers
	fmt.Printf("%s chose %s.\n", answers.Name, answers.Color)
}
```

If the format of the questions is incorrect, please inform on the correct way as the ReadMe seems to have two different ways to do it. One in the large example near the beginning, and one in the smaller examples below.

Thank you in advance for your help!

**Comment by AlecAivazis** [comment]
@rv-cpavlick thanks for reporting this error, the problem was on `survey`'s side - not yours! I'm going to push a PR with the fix now. 👍

**Comment by rv-cpavlick** [comment]
I appreciate the prompt response, thanks so much!
