### ISSUE TITLE
Option to add comment/description on multiselect option

### ISSUE THREAD

**Issue by kevhlee** [AlecAivazis/survey#432]
Hello!

So currently, we have the option to show a description for each option in a `Select` prompt. However, we do not have this option for the `Multiselect` prompt. I think `Multiselect` would also benefit from this feature. Let me know if this idea is interesting and if there are any concerns/details we need to consider.

From an initial glance, it looks like we would need to do same work that was done here: <https://github.com/AlecAivazis/survey/issues/416>. I'm open to working on this 🙂, assuming there is interest.

Thanks in advance!

**Comment by Konkrad** [comment]
Hello,
that is exactly the feature I am currently lacking. Would be interested.

**Comment by AlecAivazis** [comment]
Closed by #446

**Comment by boksasp** [comment]
Hi there. When can we expect a release with this change?

**Comment by boksasp** [comment]
Wow - great response time 🏎️  
Thanks!
