### ISSUE TITLE
Support for running "Cygwin" (MinGW/MSYS) terminals on Windows

### ISSUE THREAD

**Issue by afbjorklund** [AlecAivazis/survey#433]
Currently the posix code is compiled out, so it's **not** possible to run it from Windows.

But when `isatty.IsCygwinTerminal`, it should be preferred over the `isatty.IsTerminal`

This is the terminal:

https://mintty.github.io/

---

The library might need some refactoring, to have access to both of the implementations ?

The simple code can be copy/paste'd, but that would look ugly for e.g. cursor and such

**Comment by afbjorklund** [comment]
Apparently a duplicate of #148, which used `winpty.exe` as a workaround

* https://github.com/AlecAivazis/survey/issues/148

**Comment by AlecAivazis** [comment]
Closing this as a duplicate
