### ISSUE TITLE
Hope can controls the width of each line and displays the number of characters entered

### ISSUE THREAD

**Issue by robertzhangwenjie** [AlecAivazis/survey#440]
Now, i am using this library to implement a git commit message generator.  Although i can control the max length of prompt, i would like to have a feature that can display the number of characters entered and  can wrap  lines automatically according to  width。

The example below demonstrates this feature.
https://github.com/JosephNaberhaus/go-mitizen/blob/56f603fd666f72f69563a31175513f2a281f6334/meta/commit.gif

**Comment by mislav** [comment]
Hi, thank you for the feature request, but adding a character count to a text input is highly application-specific and I feel that it doesn't belong in this library. What you can do is make your own custom component, i.e. copy [the Multiline component](https://github.com/AlecAivazis/survey/blob/master/multiline.go) into your app and customize it there with the UI of your choice. Survey library will accept any object as long as it [implements Prompt](https://github.com/AlecAivazis/survey/blob/e47352f914346a910cc7e1ca9f65a7ac0674449a/survey.go#L123-L129).
