### ISSUE TITLE
[bugs] validation.go run error

### ISSUE THREAD

**Issue by YouZhengChuan** [AlecAivazis/survey#53]
golang version 18
MacOS 10.12.4

$ go run examples/validation.go
# command-line-arguments
examples/validation.go:13: cannot use "What is your name?" (type string) as type core.Renderer in field value
examples/validation.go:13: too few values in struct initializer
examples/validation.go:18: cannot use "Enter 'foo':" (type string) as type core.Renderer in field value
examples/validation.go:18: too few values in struct initializer

**Comment by AlecAivazis** [comment]
Thanks for reporting this @YouZhengChuan - i have been meaning to cherry pick this fix from one of my branches onto master. Will do that now so the examples run 👍

**Comment by AlecAivazis** [comment]
Please let me know if you're still having trouble running the examples

**Comment by YouZhengChuan** [comment]
Trouble has been resolved, very grateful.
