### ISSUE TITLE
Help field for inputs does not seem to be working

### ISSUE THREAD

**Issue by rv-cpavlick** [AlecAivazis/survey#54]
Getting an error of 'unknown field 'Help' in struct literal of type survey.Input' when running something like this:

``` golang
Prompt: &survey.Input{
			Message: "What is the site domain?",
			Help:    "The site name DOES contain the TLD (like '.com')",
		},
```

**Comment by AlecAivazis** [comment]
Hmm is there a chance that you are using an old version? What does your import statement look like? If I remember correctly, you're using a posix-based terminal right? I'll run the tests on my laptop but I'm pretty sure this should work for you.

**Comment by rv-cpavlick** [comment]
You are correct, it was my folly. Importing "gopkg.in/AlecAivazis/survey.v1" as opposed to github.com/AlecAivazis/survey"  fixed my problem. Thanks for another timely response.

**Comment by AlecAivazis** [comment]
No problem at all! Glad it was something simple - a word of warning, there is a known bug with the input/confirm prompts on windows. Not sure if you need windows support for what you're doing but I thought I should just mention it.

**Comment by rv-cpavlick** [comment]
Thanks for the heads up!
