### ISSUE TITLE
Add flag to turn off interactive mode

### ISSUE THREAD

**Issue by AlecAivazis** [AlecAivazis/survey#6]
The idea is to be able to switch between the two experiences in inquirer and npm

**Comment by mijdavis2** [comment]
Really like the idea, but sounds like something you'd implement in a cli. I could see using survey incorporated with something like [cobra](https://github.com/spf13/cobra). Creating a ```--non-interactive``` flag in a cobra app. If unused, run survey's ```ask``` then hand over the answers to the cobra arg parser/setter.

**Comment by AlecAivazis** [comment]
@mijdavis2 first off, thanks for commenting. I was thinking that rather than having the non-interactive version be flag driven, instead to go through the series of questions without all of the graphical fanciness that `survey` provides out of the box

**Comment by mijdavis2** [comment]
Ah that makes sense.
