### ISSUE TITLE
usability issues for Select and MultiSelect with many options

### ISSUE THREAD

**Issue by coryb** [AlecAivazis/survey#61]
As I run through my projects and replace prompts with `survey` I found a few minor usability issues with `Select` and `MultiSelect`.  Specifically if they have many options it can be too much to present all at once.   So here is a dumb example:
```
? Pick a number:
  1
  2
  3
  4
❯ 5
  6
  7
  8
  9
  10
```
I would like to add a property to limit the view, perhaps `ViewSize` so we can focus on just a few options.  So setting `ViewSize: 5` we would see something like:
```
? Pick a number:
  3
  4
❯ 5
  6
  7
```

But we would probably need some markers to indicate there is more Up or Down, so maybe something more like:
```
? Pick a number:
▲ 3
  4
❯ 5
  6
▼ 7
```

The next issue is that I would like to enable text focusing for long lists.  If you have a `Select` list of all the US States, you currently would have to hit the Down arrow 49 times to get to Wyoming.  Ideally we allow users to just type in `W` and jump the focus to the closest match starting with the letter.

**Comment by AlecAivazis** [comment]
Good point @coryb. I think the up/down indicators are a good solution, but I'll keep thinking about different ways to solve this in case i think of something different. Also, I like the idea of filtering on a select/multi-select - does the text show up while the user types?

I wonder if having a long list like the examples you showed is reason to look into a multi-column prompt...

**Comment by AlecAivazis** [comment]
Something tells me we would be able to figure out how big to make the pages by looking at the cursors current location and comparing it to the terminal height. Not sure what the windows calls look like for that just yet, but I suspect it's doable.

**Comment by coryb** [comment]
The text does not show up while typing in select/multi-select, `echo` is disabled in the terminal so that we can interpret up/down arrows etc.

My feeling is that multi-column prompts would probably be pretty confusing to users, at least I don't recall ever having seen a multi-column prompt on a console.  It might be an interesting option to play with, but I would want that behavior optional.

I think a reasonable default for the view size would be the terminal hight (when terminal height is smaller then options size), but I generally want the view size to be much smaller, probably closer to 5 lines typically.

**Comment by AlecAivazis** [comment]
Currently, it is true that `echo` is disabled on those prompts but if we end up allowing the user to jump to particular options, we probably want to give the user a way to see what they're typing. It doesn't seem likely that the options will always be in alphabetical order so if the user wants to search by one character, they will probably want to enter a second.

re the multicolumn - I think `readline` popularized the multi-column prompt, I have seen it in the autocomplete that `zsh` uses.  I think regardless the pagination of select/multi select makes sense i was mostly just bringing it up for the sake of exploration.

**Comment by AlecAivazis** [comment]
I think the major issue here was addressed by #72, there is still a small need for some sort of indicator when the contents are paginated. I started to implement the message found in inquirer felt that it only really showed when content is below, the user would have to remember that there is also content above. I think the arrows you had above address this nicely but I wanted to spend some time thinking about alternative before messing with the templates too much.

**Comment by jstrachan** [comment]
I've hit a similar issue; survey works awesome for most of my use cases (thanks!) - apart from select/multi-select lists that are huge.

I wonder if we could have a `Filter` flag on the `Select/MultiSelect` so that it allows the user to type some characters next to the field being entered to filter the selection list below.
```
? Pick a county:
 > Aaaaa
    bbb
    ccc
    ...
```

Then the user hits `t`
```
? Pick a county: t
 > Taa
     tbb
     tcc
     ccc
```
Then hopefully we can let the up/down cursor keys and space work as before to select/unselect?

**Comment by AlecAivazis** [comment]
@jstrachan I really like this idea! It shouldn't be too hard to get the arrow keys to work alongside `Filter`. 

I'm really busy at the moment so I'm not sure when I'll be able to get to this. If you want some guidance on adding this yourself, I would love to provide whatever you need. You can find me on the golang slack channel if you need help 😀

**Comment by jstrachan** [comment]
I've managed to get this working - I was surprised how little code needed to be changed ;). 

Here's a PR: https://github.com/AlecAivazis/survey/pull/125

I wasn't 100% sure what key strokes should clear a filter in addition to delete/backspace - so I added a Ctrl-W and Ctrl-X as 'clear filter' keystrokes.

**Comment by jstrachan** [comment]
@AlecAivazis btw sorry it took me so long! :)

**Comment by AlecAivazis** [comment]
@jstrachan - thanks so much for putting this together! I really appreciate the work.

I'm at work right now and can't review your PR but I will take a look later tonight when I get home. No worries at all about "taking so long", i didnt have any expectations and am just happy to see a new contributor! I'm happy to hear that you found the `terminal` package easy to work with 😄

**Comment by jstrachan** [comment]
@AlecAivazis thanks! it was actually super simple to do & barely any code changes required (just keeping track of the filter and adding the filter to the rendered template). 

I'd initially put this PR off as I thought it was gonna be super complicated & take a few days of noodling - turned out to just be an hour! :)
