### ISSUE TITLE
Add support for MultiValue prompts

### ISSUE THREAD

**Issue by jdoklovic** [AlecAivazis/survey#65]
This is slightly different than multi-select in that it can be used to gather things like "tags".
e.g.: 
? enter a tag:
    user enters: "golang"
? add another (y/n)
    user enters "y"
? enter a tag:
    user enters "github"
? add another (y/n)
    user enters "n"
... move on to next question

**Comment by AlecAivazis** [comment]
Hey @jdoklovic thanks for the suggestion. My gut says that this is a prompt that should be built on top of survey rather than integrated into the core package. It should be pretty easy to build this out into a single `Prompt`.
