### ISSUE TITLE
Add support for map[string]interface{} as a result

### ISSUE THREAD

**Issue by jdoklovic** [AlecAivazis/survey#66]
Currently you can pass a struct with fields to gather answers, however this is not very dynamic and requires the fields to be known up front.

It would be great to be able to pass map[string]interface{} as the thing to populate answers, however currently it fails due to type casting...
`reflect.Set: value of type string is not assignable to type map[string]interface {}`

**Comment by AlecAivazis** [comment]
Closing this alongside #67
