### ISSUE TITLE
MultiSelect does not support cycling through the list

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#71]
If I hit <kbd>Up</kbd> key at the beginning of the list, it should go to the item at the end of the list.

Similarly, if I hit <kbd>Down</kbd> at the end of the list, it should cycle back to the item at the beginning of the list.

This behavior is supported by Inquirer.js.

**Comment by canghai908** [comment]
I also have this questions

**Comment by AlecAivazis** [comment]
Thanks again for reporting this @ahmetb!

@ahmetb @canghai908 - I decided to spend a little time today to address this have fixed it in a branch. I'm going to look into fixing #70 as well before I cut a new release but hopefully that won't take too long. I'll keep this issue open until the branch is merged and let u guys know when u can expect to see this in your projects.

**Comment by AlecAivazis** [comment]
@ahmetb @canghai908 you should be able to see the current selects cycling through the pages when you navigate past the bounds - lemme know if you run into any more issues.
