### ISSUE TITLE
MultiSelect scrolling not obvious

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#73]
When I presented a MultiSelect with a long list it's not clear to the user whether there are more items beyond `Item 6` (there is 100 more items).

![image](https://user-images.githubusercontent.com/159209/27990005-883a594e-63fd-11e7-977d-bf9dba217753.png)

Inquirer.js communicates this better as they print a gray `(Move up and down to reveal more choices)` line at the bottom: 

![image](https://user-images.githubusercontent.com/159209/27990017-c362fefe-63fd-11e7-9de7-92ee8fca8e0b.png)

I see there's an empty line at the end of MultiSelect in `survey` package currently. Did you mean to add this note and forget about it perhaps?

**Comment by AlecAivazis** [comment]
Hey @ahmetb thanks for reporting this issue. I want to add a notification of the pagination to the prompt but wanted to evaluate the possibilities before comitting to inquirers design. @coryb and I are discussing this in #61 - mind if we move the conversation there? Also I’d love to hear what u thInk about cory’s proposal.
