### ISSUE TITLE
Required Validation does not work for MultiSelect

### ISSUE THREAD

**Issue by wburningham** [AlecAivazis/survey#77]
The code panics if you try to use a MultiSelect question with the built in Required validator.

**Comment by AlecAivazis** [comment]
Thanks for reporting this @wburningham. I was able to reproduce it and will try to get a fix out when I get back from work today.

**Comment by AlecAivazis** [comment]
@wburningham I just pushed a PR with a fix for this bug. Once it's merged, i'll cut a release with the fix ASAP. Thanks again for reporting the issue!

**Comment by AlecAivazis** [comment]
This should be fixed in `v1.2.2` please let me know if you're still running into it.
