### ISSUE TITLE
A simple way to ask one question at a time

### ISSUE THREAD

**Issue by mholt** [AlecAivazis/survey#8]
I have a situation where a fair amount of logic needs to happen between each question, and it would be good to be able to do something like this:

```go
answer, err = survey.AskOne(&survey.Choice{
	Message: "...",
	Choices: []string{"..."},
})
```

What do you think?

**Comment by mholt** [comment]
I implemented this simply:

```go
func askOne(p survey.Prompt) string {
	answers, err := survey.Ask([]*survey.Question{{Name: "q1", Prompt: p}})
	if err != nil {
		log.Fatal(err) // or whatever
	}
	return answers["q1"]
}

// Usage:
answer := askOne(&survey.Choice{
	Message: "...?",
	Choices: []string{"..."},
})
```

But it might be nice to see this available in the package itself.

**Comment by AlecAivazis** [comment]
I like this idea - if you had time to submit a PR I would gladly merge it in. I would do it myself but I think I will be pretty busy with the other issues.

**Comment by AlecAivazis** [comment]
Just curious, what sort of logic needs to happen? I'm wondering if there is something `survey` could be providing that would better support what you needed.

**Comment by mholt** [comment]
It's application-specific. In one case, I quit entirely ("are you sure you want to continue?" kind of thing). But yes, other times it is to add an extra follow-up question or to skip questions.

So I actually use your package more for getting input rather than doing an actual survey. I like how it formats the output and does multiple-choice, especially. Very pleasing to read and use. So I find myself asking one question at a time rather than batching them.

So I dunno how complicated you want your API to get, but if you felt like users need a more comprehensive solution you could consider something like a "computation graph" but with questions instead of computations. For each question, you'd need a function that maps possible answers to next questions.
