### ISSUE TITLE
Document where answers can be written to

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#81]
I've been collecting answers to survey.MultiSelect etc. prompts into a `[]string`. But from the source code it looks like it's possible to use structs/maps too? https://github.com/AlecAivazis/survey/blob/6ee49f5e0a0ffadd78f5cd8c0b9429d84439846e/core/write.go#L19

If that's the case, Ask/AskOne methods that visibly accept `t interface{}` should probably document this behavior what `t`'s type should/can be.

**Comment by AlecAivazis** [comment]
`WriteAnswer` handles the copying of the returned value from the prompt into whatever pointer you pass into `Ask`/`AskOne`. `[]string` is the right return type for a `MultiSelect` prompt, currently it does not support writing to anything else but I will address that as part of #84

**Comment by AlecAivazis** [comment]
I"m going to close this - if you feel like I should add more documentation, please open another ticket :)
