### ISSUE TITLE
Support MultiSelect/Select for survey.Required validator

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#83]
I think the survey.Required validator logically makes sense for Select/MultiSelect, too.

However using it as a validator in MultiSelect currently gives the following error:

```
panic: runtime error: comparing uncomparable type []string

goroutine 1 [running]:
github.com/AlecAivazis/survey.Required(0x145c0e0, 0xc420216620, 0xc420216620, 0x0)
	/Users/ahmetb/workspace/gopath-iamutil/src/github.com/AlecAivazis/survey/validate.go:12 +0xc7
github.com/AlecAivazis/survey.Ask(0xc4200b1b90, 0x1, 0x1, 0x1447700, 0xc4201fb1e0, 0x80, 0x1500de0)
	/Users/ahmetb/workspace/gopath-iamutil/src/github.com/AlecAivazis/survey/survey.go:61 +0x16e
github.com/AlecAivazis/survey.AskOne(0x1762aa0, 0xc4202c7300, 0x1447700, 0xc4201fb1e0, 0x15450a8, 0x0, 0x0)
	/Users/ahmetb/workspace/gopath-iamutil/src/github.com/AlecAivazis/survey/survey.go:32 +0xbe
```

It would be cool to use this validator (or a new one, like survey.HasAnswer) that works with slice semantics.

**Comment by AlecAivazis** [comment]
Hello again @ahmetb, I'm pretty sure this issue was resolved on the latest release of the package. [here](https://github.com/AlecAivazis/survey/issues/77) is the original report. Can u verify you have v1.2.2 installed?

**Comment by ahmetb** [comment]
I just did a go get -u, seems to be fixed. Thanks.
