### ISSUE TITLE
Allow users to set output stream

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#85]
It users like this library is printing interactive dialogues to stdout. This is making it difficult to write programs that prompt questions, which then prints something to stdout users can redirect to a file and use.

e.g. A program like

    keyutil generate --to-file=- | jq .

Would print to stdout, which then would be consumed by the next program in the pipeline. However currently all questions go to stdout, making this impossible.

**Comment by karuppiah7890** [comment]
What should be the output (to file or stdout) ? The questions and the answers together ? Or just the answers ? And in case of questions - the complete message of the question or just the name of the question which is used to identify the question and get the answer currently

**Comment by ahmetb** [comment]
so answers are already in STDIN, they don't need to be in any of the output streams.

however, the questions, animations etc, they can go to STDERR (hopefully we're not expecting people to save ansi escape sequences we use to do animations to files).

this way I can easily write a program that only prints to STDOUT from my code and not from the `survey` package.

**Comment by ahmetb** [comment]
I still need this feature and may take a look at it. Or would you like to tackle it yourself @AlecAivazis ? It looks like all the changes required would be in this repo.

**Comment by AlecAivazis** [comment]
hey @ahmetb! Sorry for not responding - if you want to submit a PR with some test cases I would love to review it. I agree that sending only the results to `stdout` is probably the way to go. sending the animation stuff to stderr feels a bit weird but I'm not sure what else to do...

Looking forward to seeing it implemented!

**Comment by AlecAivazis** [comment]
I'm going to close this since #143 has been merged. If it doesn't address your exact needs @ahmetb, feel free to open another issue
