### ISSUE TITLE
gokpg.in version uses github/.../core instead of gopkg.in/.../core

### ISSUE THREAD

**Issue by mhils** [AlecAivazis/survey#89]
Hi,

I'm hope I'm not holding it wrong, but I just ran into the following issue which took me some time to debug. Following https://github.com/AlecAivazis/survey#customizing-output, I tried the following:
```golang
package main

import (
	surveyCore "gopkg.in/AlecAivazis/survey.v1/core"
	"gopkg.in/AlecAivazis/survey.v1"
)

func main() {
	surveyCore.QuestionIcon = "???"

	options := []string{"Chicken", "Egg"}
	var ret string
	prompt := &survey.Select{
		Message: "Which came first, the chicken or the egg?",
		Options: options,
	}
	survey.AskOne(prompt, &ret, nil)
}
```
However, that does not change the question icon. After some debugging, I found that I need to reference the GitHub package to get it work:
```diff
diff --git a/icon.go b/icon_fixed.go
index b94e586..8e09228 100644
--- a/icon.go
+++ b/icon_fixed.go
@@ -1,8 +1,8 @@
 package main

 import (
+       surveyCore "github.com/AlecAivazis/survey/core"
        "gopkg.in/AlecAivazis/survey.v1"
-       surveyCore "gopkg.in/AlecAivazis/survey.v1/core"
 )

 func main() {
```
Without being a Go expert, this seems wrong as it effectively breaks semantic versioning?

Thanks for the fantastic project!

**Comment by AlecAivazis** [comment]
Hey @mhils! Thanks for reporting this. You are correct - this should be fixed. I'll try to get something out by the end of the week (hopefully tonight).

**Comment by AlecAivazis** [comment]
@mhils, i just pushed a PR which should hopefully fix this - thanks again for reporting!

**Comment by mhils** [comment]
Fantastic, thanks! 😃 🍰
