### ISSUE TITLE
Answers can only be one word

### ISSUE THREAD

**Issue by mholt** [AlecAivazis/survey#9]
Sorry for the flood of issues. Having a lot of fun with this lib though. :smile:

Using the demo in the README, it seems that the survey.Input prompt truncates answers to just the first word. (Try using something like "hello dolly" as the answer.)

I'm on a roll with something, or I'd submit a patch right now -- maybe sometime in the future if you can't get around to it, however I'm not super familiar with terminal-fu.

**Comment by AlecAivazis** [comment]
No worries about the issues. Glad to see you're having fun with it. I knew there were going to be a bunch of edge cases so I'm happy to have another pair of eyes. 

I'll try reproducing this right away and take a stab at a fix. Thanks again!
