### ISSUE TITLE
Fix correct versioning of releases

### ISSUE THREAD

**Issue by mandrean** [AlecAivazis/survey#95]
Currently, some releases are incorrectly tagged in GitHub (missing the `v` prefix before e.g. `1.3.1`):

<img width="486" alt="skarmavbild 2017-09-29 kl 18 56 02" src="https://user-images.githubusercontent.com/4631744/31026780-f4266194-a547-11e7-8870-9b44a4d6a832.png">

This causes `gopkg` to not pick up these versions:

<img width="718" alt="skarmavbild 2017-09-29 kl 18 57 40" src="https://user-images.githubusercontent.com/4631744/31026843-2902c934-a548-11e7-9e47-903dbede9a04.png">

Which means that if you use `github.com/AlecAivazis/survey` you get build errors, and if you use `gopkg.in/AlecAivazis/survey.v1/survey` you get an older version without e.g. `survey.Editor` ¯\_(ツ)_/¯ 

<img width="530" alt="skarmavbild 2017-09-29 kl 18 53 57" src="https://user-images.githubusercontent.com/4631744/31026917-857b3048-a548-11e7-964f-af034d01a8fe.png">

**Comment by mandrean** [comment]
To fix this, run these commands:

```sh
# create new correct tags from old incorrect ones
git tag v1.3.0 1.3.0
git tag v1.3.1 1.3.1

# delete incorrect tags locally
git tag -d 1.2.4 1.3.0 1.3.1

# delete incorrect tags remotely
git push origin :refs/tags/1.2.4
git push origin :refs/tags/1.3.0
git push origin :refs/tags/1.3.1

# push new tags remotely
git push origin --tags
```

Then you can go into https://github.com/AlecAivazis/survey/releases and update the releases for `1.3.0` and `1.3.1` so they use the new tags instead.

**Comment by AlecAivazis** [comment]
Thanks for reporting this @mandrean. I just fixed the release names on github - hopefully that fixes the `gopkg.in` imports. Mind giving it a try? I'll close this issue once you confirm it's working.

**Comment by AlecAivazis** [comment]
So maybe I executed the wrong steps, but the above commands seem to have overwritten the sha referenced by the different versions so they weren't really unique releases anymore. In order to avoid confusion, i've removed the duplicate releases and made sure the most recent release has a `v` at the beginning.

**Comment by mandrean** [comment]
@AlecAivazis Actually, creating/deleting/renaming tags doesn't change SHA hashes. Only commits do. Tags are just references to existing SHA hashes. You can always go back years later and tag a certain commit hash as a release (if you would ever want to).

You do, however, have to update the **GitHub Release** manually after changing a tag. When you rename `1.2.4` to `v1.2.4`, the release associated with that tag becomes a draft. You have to click the edit button for the release and pick `v1.2.4` as its git tag. Then it will be all good.

Anyway, releasing `v1.3.4` is good enough for me. Thanks!
