### ISSUE TITLE
Tab-completion on file paths for input 

### ISSUE THREAD

**Issue by mattstratton** [AlecAivazis/survey#96]
I realize this might be super challenging, but one of the things I have in my cli app using survey is a place for users to enter the path to a local file. Tab-completion of the path would be super great. Has anyone taken a whack at this?

**Comment by AlecAivazis** [comment]
Oo i really like this idea. I don't think anyone has attempted it yet, but it would definitely be useful. One thing to add is that a user might not always want the tab-complete so we should probably set it as an opt-in feature of the `Input` prompt. If you want to take a stab at it, i'd be more than happy to review the PR.

**Comment by AlecAivazis** [comment]
I'm going to close this as it has gone very stale

**Comment by lucassabreu** [comment]
@AlecAivazis just to be sure, this is not implemented today right? if not is okey if i try to do it?

**Comment by AlecAivazis** [comment]
Hey @lucassabreu, you are correct this has not been implemented yet. I will go ahead and reopen the issue, feel free to take it on :)

**Comment by infixint943** [comment]
> Hey @lucassabreu, you are correct this has not been implemented yet. I will go ahead and reopen the issue, feel free to take it on :)

I'll take it up :)

**Comment by lucassabreu** [comment]
i did not answer... but i already started it

**Comment by AlecAivazis** [comment]
thanks @lucassabreu!
